name: logger_flutter
description: Flutter extension for logger. Please go there for documentation.
version: 1.1.2
author: Simon Leier <simonleier@gmail.com>
homepage: https://github.com/leisim/logger_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger:
    git: https://github.com/FMotalleb/logger.git
  sensors_plus: ">=1.3.2"
  share_plus: ^4.0.10
